[build]
builder = "NIXPACKS"

[build.buildCommand]
cmd = "npm install"

[build.startCommand]  
cmd = "npm start"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
NODE_ENV = "production"